<a href="https://colab.research.google.com/github/milnico/masterAI4HU/blob/main/Lezione4__numpy_svolta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.
To use Numpy, we first need to import the `numpy` package:

In [ ]:
import numpy as np



A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)  

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.shape)
print(np.shape(b))
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
(2, 3)
1 2 4


In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.99695965 0.35158138]
 [0.45800497 0.87577073]]


In [ ]:
import matplotlib.pyplot as plt

np.random.seed(42)
x = np.random.uniform(size=100000)

plt.hist(x, density=False, bins=30)  # density=False would make counts
plt.ylabel('Probability')
plt.xlabel('Data');

In [ ]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:



In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify 


In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

2
77


In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x[x>2])
# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[3. 4.]
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
import time

a = np.arange(0,1000000)
sum=0
ct = time.time()
for i in a:
  sum+=i
print(sum,time.time()-ct)
ct = time.time()
print(np.sum(a),time.time()-ct)

## Esercizi

In [ ]:
#Initialize a numpy array with all the integer values from 1 to 1000, then only with values every 5, 8 and 10 integers.

In [ ]:
#Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.



In [2]:
#Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10
import numpy as np
a = np.arange(2,11)
a = np.reshape(a,(3,3))#equivalente a np.arange(2,11).reshape(3,3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [9]:
#Write a NumPy program to create a null vector of size 10 and update sixth value to 11
empty_array = np.empty(10)

empty_array[5] = 11
print(empty_array)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [36]:
import numpy as np
np.random.seed(23595959)
array = np.random.random_sample(100)
print(array)
print(array[array>0.05 and array<0.15])

[0.35017477 0.87815508 0.84153327 0.84082915 0.61867604 0.30934884
 0.62285617 0.70033952 0.60910206 0.62367998 0.23921885 0.343216
 0.46059934 0.69164385 0.41931705 0.73024148 0.80848711 0.88500231
 0.98365085 0.84434707 0.84639168 0.1044821  0.74671433 0.51529347
 0.67627575 0.40789955 0.98089944 0.5769962  0.71238706 0.443356
 0.40825145 0.17655007 0.15107784 0.04321951 0.52037491 0.85768403
 0.68443452 0.04586914 0.69752315 0.38957513 0.29586087 0.68878841
 0.6612825  0.46235472 0.39994776 0.96665581 0.35220135 0.98936429
 0.47942504 0.04075605 0.81526512 0.34470381 0.29812574 0.5087755
 0.52432657 0.08507979 0.6853133  0.20944847 0.43848302 0.44496133
 0.42267361 0.52763543 0.28949286 0.6488986  0.82001428 0.50505237
 0.76843271 0.28906735 0.67343464 0.23520345 0.44983128 0.10226336
 0.38276021 0.63377018 0.45137799 0.67588972 0.26598038 0.3878066
 0.55728693 0.11691142 0.86456198 0.40206423 0.60025716 0.39593433
 0.55902631 0.73443396 0.58602269 0.86284324 0.53512566 0.35966226
 

ValueError: ignored

In [54]:
import numpy as np
np.random.seed(22)
array = np.random.random_sample(30)
print(array)
#print(array[(array > 0.05) & (array < 0.20)])
a=0.05
b =0.25
dati = np.logical_and(array>a,array<b)
print(dati)
print(array[dati])
print(np.where(dati))

[0.20846054 0.48168106 0.42053804 0.859182   0.17116155 0.33886396
 0.27053283 0.69104135 0.22040452 0.81195092 0.01052687 0.5612037
 0.81372619 0.7451003  0.18911136 0.00614087 0.77204387 0.95783217
 0.70193788 0.29757827 0.76799274 0.68821832 0.38718348 0.61520583
 0.42755524 0.58428964 0.70263552 0.11189517 0.92326993 0.98888627]
[ True False False False  True False False False  True False False False
 False False  True False False False False False False False False False
 False False False  True False False]
[0.20846054 0.17116155 0.22040452 0.18911136 0.11189517]
(array([ 0,  4,  8, 14, 27]),)


In [68]:
#Write a NumPy program to replace all elements of NumPy array that are greater than 0.5.
import numpy as np
np.random.seed(27)
array = np.random.random_sample((5,5))
print(array)
print(array>0.5)
#print(array[array>0.5])
array[array>0.5]=10
print(array)



[[0.42572141 0.81458374 0.73539729 0.8680032  0.38338077]
 [0.97945663 0.89319435 0.20971517 0.74182765 0.66314332]
 [0.88680146 0.85801271 0.74926221 0.87014472 0.18675584]
 [0.32556672 0.37293743 0.79371303 0.15106027 0.1699427 ]
 [0.08116909 0.30517534 0.7832898  0.16290618 0.0706413 ]]
[[False  True  True  True False]
 [ True  True False  True  True]
 [ True  True  True  True False]
 [False False  True False False]
 [False False  True False False]]
[[ 0.42572141 10.         10.         10.          0.38338077]
 [10.         10.          0.20971517 10.         10.        ]
 [10.         10.         10.         10.          0.18675584]
 [ 0.32556672  0.37293743 10.          0.15106027  0.1699427 ]
 [ 0.08116909  0.30517534 10.          0.16290618  0.0706413 ]]


In [107]:
#Exercise: There two array, one with a list of names and one with the related age. Retrieve the mean of the boys' age and get the names of the elder and the younger. Using numpy
import numpy as np
names = ["Ezio", "Maria", "Pamela", "Carlo", "Fulvio", "Carmela", "Paola","Enzo"]
names = np.array(names)

ages = [12, 14, 10, 9, 11, 12, 13,9]
anni_minimi = np.amin(ages)
print(anni_minimi)
result = np.where(ages == anni_minimi)
print(names[result[0]])



9
['Carlo' 'Enzo']


In [ ]:
#write NumPy program that creates a two rank 2 array, or two matrix, of dimension (5,5), a and b.
#then append b to a to create a single rank 2 array of dimension (5,10)
#furthermore append again b to a , this time to create a single rank 2 array of dimension (10,5)



In [121]:
#Write a NumPy program to get the column numbers in given array where at least one item is larger than 3.0.

import numpy as np
np.random.seed(1)
arr1 = np.random.random_sample((4,9))*10
print(np.mean(arr1,axis=0))
#print(arr1>7.0)
#print(np.any(arr1>7.0,axis=0))
#larger = np.where(np.any(arr1>7.0,axis=0))
#print(larger)

[2.83820115 3.76862729 5.91055237 3.93348308 4.39851283 4.42484583
 5.6657054  5.87337327 3.39004286]


In [ ]:
 #Compute the maximum for each row in the given array.
 # Input
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)



[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
[9 8 6 3 9]
[9 8 6 3 9]


In [ ]:
#Create a 2-D array of dimension (10,3) and generate a new array containing its 2nd and 4th rows.



In [ ]:
#Generate a 10 x 3 array of random numbers (in range [0,1]). For each row, pick the number closest to 0.5.
import numpy as np


In [ ]:
# Initialize a random rank 2 array of dimension (5,6) of integer between 1 and 10 using the numpy function randint. Then split the matrix in 5 arrays 
# one for each row, and 6 arrays one for each column

Riempire una sequenza con 100 interi pseudo-casuali compresi tra -50 e +50 (estremi inclusi). Successivamente visualizzare il secondo intero più piccolo tra gli interi presenti nella sequenza

In [151]:
import numpy as np

x=np.random.randint(-50,51,size=100)
print(x)

x=np.random.randint(-50,51,size=100)
print(x)
x=np.random.randint(-50,51,size=100)
print(x)
x=np.random.randint(-50,51,size=100)
print(x)
#print(y[1])
#uniques = np.unique(x)
#print(uniques)
#print(uniques[1])


[-12   6 -29   1 -47  -7 -21 -49   3  31  27  10 -48 -33 -47  -2  37  13
 -26 -46  18  36  -4 -36  39   5 -32  -7  34  -7  13 -36 -34  40  27   0
 -13 -33   2 -12 -28   0  -7  32 -10 -19  35 -22  17 -12  19 -24  33  39
  30  46  38  29  25 -30  10 -16 -40  15   9  13   4 -39 -36   7 -49 -35
 -48  35 -34  15  22 -50  -5 -25   7  17   2 -44  48   0   2   2   3  -8
  50  46  33 -38  -2 -23  43 -32 -32  -1]
[ 12  32 -16 -15 -23 -32  -4  16  14 -36   3 -49  35  36  -8  11 -19  47
 -29  44 -45  -4   3  14  40 -12 -18 -10 -47 -36 -21 -40  39 -15  31 -33
 -12 -35  42 -49  23 -10  46 -12 -19   4  -6 -32   1  30  23  -8  -6  48
  16  45  15 -20  22 -11 -40 -45  11 -43 -28 -20  11  41  13 -18 -21 -39
  29  17  40 -16   2 -43  12   0  -4  32 -15  38 -21  43   7 -42 -11  36
   0  13 -42  24 -41 -50  49  40 -21 -18]
[ 12  34 -13  10  21 -29  -7  37  39   7 -30 -28 -18  27 -19  37 -27  39
 -44 -46 -27 -19  38 -48  50  27  14 -18 -37 -49   3  49 -45   4 -40 -45
   1 -40  42 -25  28  44  -6 -27  21  41

# Riempire una matrice di 4 righe e 3 colonne con interi pseudo-casuali compresi tra 1 e 9 (estremi inclusi). Per ciascuna riga della tabella visualizzare la somma degli interi presenti sulla riga e, successivamente, visualizzare la somma degli interi presenti su ciascuna colonna

In [160]:
import numpy as np

x = np.random.randint(1,10,(4,3))

print(x)
print(np.mean(x,axis=1))


[[3 8 4]
 [6 4 8]
 [2 3 3]
 [5 2 9]]
[5.         6.         2.66666667 5.33333333]


Riempire una matrice di 6 righe e 6 colonne con interi pseudo-casuali compresi tra 1 e 50 (estremi inclusi). Creare un nuovo vettore di rango 1 di 6 elementi
contenente la somma degli elementi pari di ciascuna riga

In [186]:
import numpy as np


np.random.seed(22)
mat = np.random.randint(1,51,(6,6))
print(mat)
sum = np.array([])
for row in mat:
  print(row,row[row%2==0],np.sum(row[row%2==0]))
  sum = np.append(sum,np.sum(row[row%2==0]))
print(sum)

[[ 5 45  1 37 39 44]
 [21  9 32 37 30 19]
 [15 46 25 30 40 35]
 [42  9 41  6 48 28]
 [21 35 30 19 18 39]
 [20 20  3 28  8 28]]
[ 5 45  1 37 39 44] [44] 44
[21  9 32 37 30 19] [32 30] 62
[15 46 25 30 40 35] [46 30 40] 116
[42  9 41  6 48 28] [42  6 48 28] 124
[21 35 30 19 18 39] [30 18] 48
[20 20  3 28  8 28] [20 20 28  8 28] 104
[ 44.  62. 116. 124.  48. 104.]
