<a href="https://colab.research.google.com/github/milnico/masterAI4HU/blob/main/Lezione4__numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.
To use Numpy, we first need to import the `numpy` package:

In [ ]:
import numpy as np



A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)  

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.shape)
print(np.shape(b))
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
(2, 3)
1 2 4


In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.99695965 0.35158138]
 [0.45800497 0.87577073]]


In [ ]:
import matplotlib.pyplot as plt

np.random.seed(42)
x = np.random.uniform(size=100000)

plt.hist(x, density=False, bins=30)  # density=False would make counts
plt.ylabel('Probability')
plt.xlabel('Data');

In [ ]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:



In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify 


In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

2
77


In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x[x>2])
# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[3. 4.]
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
import time

a = np.arange(0,1000000)
sum=0
ct = time.time()
for i in a:
  sum+=i
print(sum,time.time()-ct)
ct = time.time()
print(np.sum(a),time.time()-ct)

## Esercizi

In [ ]:
#Initialize a numpy array with all the integer values from 1 to 1000, then only with values every 5, 8 and 10 integers.

In [ ]:
#Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.



In [ ]:
#Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10


In [ ]:
#Write a NumPy program to create a null vector of size 10 and update sixth value to 11


In [ ]:
#Write a NumPy program to replace all elements of NumPy array that are greater than 0.5.



In [ ]:
#write NumPy program that creates a two rank 2 array, or two matrix, of dimension (5,5), a and b.
#then append b to a to create a single rank 2 array of dimension (5,10)
#furthermore append again b to a , this time to create a single rank 2 array of dimension (10,5)



In [2]:
#Write a NumPy program to get the row numbers in given array where at least one item is larger than 10.

import numpy as np
num = np.arange(36)
arr1 = np.reshape(num, [4, 9])

In [ ]:
 #Compute the maximum for each row in the given array.
 # Input
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)



[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
[9 8 6 3 9]
[9 8 6 3 9]


In [ ]:
#Create a 2-D array of dimension (10,3) and generate a new array containing its 2nd and 4th rows.



In [1]:
#Generate a 10 x 3 array of random numbers (in range [0,1]). For each row, pick the number closest to 0.5.
import numpy as np


In [ ]:
# Initialize a random rank 2 array of dimension (5,6) of integer between 1 and 10 using the numpy function randint. Then split the matrix in 5 arrays 
# one for each row, and 6 arrays one for each column

Riempire una sequenza con 100 interi pseudo-casuali compresi tra -50 e +50 (estremi inclusi). Successivamente visualizzare il secondo intero più piccolo tra gli interi presenti nella sequenza

Riempire una matrice di 4 righe e 3 colonne con interi pseudo-casuali compresi tra 1 e 9 (estremi inclusi). Per ciascuna riga della tabella visualizzare la somma degli interi presenti sulla riga e, successivamente, visualizzare la somma degli interi presenti su ciascuna colonna

Riempire una matrice di 6 righe e 6 colonne con interi pseudo-casuali compresi tra 1 e 50 (estremi inclusi). Creare un nuovo vettore di rango 1 di 6 elementi
contenente la somma degli elementi pari di ciascuna riga